---
apiVersion: v1
kind: Namespace
metadata:
  name: componentgroup-sample-minimal-v2
---
apiVersion: appstudio.redhat.com/v1beta2
kind: ComponentGroup
metadata:
  labels:
    app.kubernetes.io/name: componentgroup-v2
    app.kubernetes.io/instance: componentgroup-sample-minimal-v2
    app.kubernetes.io/part-of: integration-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: integration-service
  name: componentgroup-sample-minimal-v2
spec:
  components:
    - name: first-component
      componentBranch:
        name: "main"
        lastPromotedImage: quay.io/sampleorg/first-component@sha256:1b29...
        lastPromotedCommit: 6a7c81802e785aa869f82301afe61f4e9775772b
        lastBuildTime: "2025-08-13T05:13:25Z"
    - name: second-component
      componentBranch:
        name: "main"
        lastPromotedImage: quay.io/sampleorg/second-component@sha256:ae32...
        lastPromotedCommit: 1359836353b8e249f2fbceba47d82751d7dab902
        lastBuildTime: "2025-08-13T05:13:25Z"
    - name: third-component
      componentBranch:
        name: "main"
        # if a component has not been built yet these fields will be empty
        lastPromotedImage: ""
        lastPromotedCommit: ""
        lastBuildTime: ""
