## Append samples you want in your CSV to this file as resources ##
resources:
- appstudio_v1alpha1_integrationscenario.yaml
- appstudio_v1alpha1_integration.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
