# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/appstudio.redhat.com_integrationtestscenarios.yaml
- bases/appstudio.redhat.com_componentgroups.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
- path: patches/webhook_in_integrationtestscenarios.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: integrationtestscenarios.appstudio.redhat.com
- path: patches/oneof_in_integrationtestscenarios.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: integrationtestscenarios.appstudio.redhat.com
  options:
    allowKindChange: false
    allowNameChange: false

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_integrationtestscenarios.yaml
#  target:
#    group: apiextensions.k8s.io
#    version: v1
#    kind: CustomResourceDefinition
#    name: integrationtestscenarios.appstudio.redhat.com

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
